kind: Pod
apiVersion: v1
metadata:
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Customer-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3