kind: Pod
apiVersion: v1
metadata:
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - liveness
    ports: 
    - name: liveness-port
      containerPort: 8080 
    livenessProbe:
      httpGet:
        path: /healthz
        port: liveness-port         # use the name of the port
        httpHeaders:
        - name: Customer-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3

      # You can use a named port for HTTP and TCP probes. gRPC probes do not support named ports.