kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv
  namespace: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data