apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  namespace: nginx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: name
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
